DirectoryPath: public
IgnoreURLs:
  # These domains block htmltest
  - "blogspot.com"
  - "linkedin.com"
  - "soundcloud.com"
  - "speakev.com"
  - "t.co"
  - "twitter.com"
CheckMeta: false
ExternalTimeout: 60
