language: ruby
rvm:
- 2.3.4
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
    - imagemagick # for generating poster images for videos

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./ci/build.sh

# Only build pushes to the master branch
branches:
  only:
  - master

deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  repo: kevincon/kevincon.github.io
  target-branch: master
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    condition: '"$TRAVIS_EVENT_TYPE" != "cron"'

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
