# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kevin Technology
description: >- # this means to ignore newlines until the next key
  My name is Kevin Conley, and I am a versatile software engineer
  who loves improving developer productivity and infrastructure. \\
   \\
  I currently work on validating firmware for SSDs at [Intel](https://www.intel.com/content/www/us/en/products/memory-storage/solid-state-drives.html). \\
   \\
  Previously I worked on graphics, UI, and application firmware for the
  [Intel Vaunt smart glasses](https://www.theverge.com/2018/2/5/16966530/intel-vaunt-smart-glasses-announced-ar-video)
  and several smart watches at [Pebble](https://en.wikipedia.org/wiki/Pebble_(watch)).
copyright: © 2020 Kevin Conley
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kevintechnology.com" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Kevin Conley
  email: mail@kevintechnology.com
  social:
    twitter: kevindcon
    github: kevincon
    linkedin: kevincon
    email: mailto:mail@kevintechnology.com
google_analytics: UA-17601169-1
disqus: kevintechnology
paginate: 5
paginate_path: '/page-:num/'
accent_color: '#137ed9'
accent_image: none
hydejack:
  post_addons: [related, comments]
  no_large_headings: true
  no_navbar: true
  no_search: true
  no_push_state: true
  no_mark_external: true
defaults:
  - scope:
      type: posts
    values:
      comments: true

# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack
plugins:
  - jekyll-feed
  - jekyll_oembed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-youtube
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Rakefile
