name: Continuous Integration
on:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # We run this workflow weekly at midnight on Sundays
    - cron:  '0 0 * * SUN'
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Pre-commit
        uses: devcontainers/ci@v0.3
        with:
          runCmd: pre-commit run --all-files
      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          runCmd: hugo --minify --verbose
      - name: Test
        uses: Wandalen/wretry.action@v3
        with:
          action: devcontainers/ci@v0.3
          attempt_limit: 3
          attempt_delay: 2000 # ms
          with: |
            runCmd: htmltest
