name: Continuous Deployment
on:
  push:
    branches: [ master ]
jobs:
  build_and_test_and_deploy:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Pre-commit
        uses: devcontainers/ci@v0.3
        with:
          runCmd: pre-commit run --all-files
      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          runCmd: hugo --minify --verbose
      - name: Test
        uses: devcontainers/ci@v0.3
        with:
          runCmd: htmltest
      - name: Check GitHub Pages Status
        uses: crazy-max/ghaction-github-status@v3
        with:
          pages_threshold: partial_outage
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: public
          fqdn: kevintechnology.com
          keep_history: false
          jekyll: false
          repo: kevincon/kevincon.github.io
          target_branch: master
        env:
          GH_PAT: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
