name: Continuous Integration
on:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # We run this workflow weekly at midnight on Sundays
    - cron:  '0 0 * * SUN'
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
          # Note this line takes care of installing our dependencies
          bundler-cache: true
      - name: Build and Test
        run: bundle exec rake test
